### ISSUE TITLE
OCaml like Module System

### ISSUE THREAD

**Issue by sirinath** [oden-lang/oden#102]
Is it possible to more the package system 1st class?

**Comment by owickstrom** [comment]
Hi,

I wish I had a better understanding of the OCaml module system, but from what I've read I'm not sure that it will fit with the current design of Oden. Do you have any practical example of code you'd want to write using first-class modules? I'd be happy to explore how such code would be written in Oden.

Thanks!

**Comment by sirinath** [comment]
What I am looking for is one module being able to be replaced by another module which has equivalent functionality and the module being able to be passed to functions. Basically a module will be treated as a record.

**Comment by owickstrom** [comment]
OK! If I'm not misunderstanding you, this is basically covered by _protocols_ in Oden. Have a look at https://oden-lang.org/user-guide/latest/#protocols in the User Guide. You define a protocol with the *methods* supported (equivalent to the signatures in the OCaml module?) and provide/import implementations for your specific types. Depending on the inferred type of a protocol method reference, the compiler will choose an implementation. This works similarly as *type classes* in Haskell.

**Comment by owickstrom** [comment]
I'm closing this due to the inactivity. If you want to continue the discussion I suggest we move it to https://groups.google.com/forum/#!forum/oden-lang.

Thank you!
