### ISSUE TITLE
Logical operators not implemented

### ISSUE THREAD

**Issue by chribben** [oden-lang/oden#16]
`and`, `or` and `not` are not implemented. When compiling e.g. the expression `(or true false)` it will output *Type check failed!*

**Comment by owickstrom** [comment]
Thanks for reporting. Working on this now. :)

**Comment by owickstrom** [comment]
```(pkg main)

(import fmt)

(define (main) (fmt.Println (if (or (not false) false) "yes" "no")))

**Comment by owickstrom** [comment]
This should work now, also released in the [Playground](https://oden-playground.herokuapp.com/).

```scheme
(pkg main)

(import fmt)

(define (main) (fmt.Println (if (or (not false) false) "yes" "no")))
```
