### ISSUE TITLE
Polymorphic function definitions

### ISSUE THREAD

**Issue by owickstrom** [oden-lang/oden#2]
- [x] Defining a type polymorphic function at the top level should enable the use of it from other code and compile all such instances as monomorphed Go functions.
- [x] Unbound logic variables should be replaced with type variable symbols when defining a polymorphic function.
- [x] When calling a polymorphic function the type variables should be substituted back for logic variables in that calls infer process.

### Consider:
* Type variable symbols and how not to clash with types? Upper/lowercase rules?
* (Possibly inlining could be useful as well?)

**Comment by vessenes** [comment]
Just a small comment on inlining: the current state of the go compiler's escape analysis means that it's often a large win to inline functions. Especially if it's all generated by odenc, I would recommend you by default inline almost everything. 

Of course, it's worth doing some testing, and for very large programs there's a compile-runtime tradeoff, but we've found that it's usually worth inlining.

**Comment by owickstrom** [comment]
@vessenes cool, thank you for your insights! I'm thinking that monomorphisation will be A LOT simpler if `odenc` does inlining of these calls. Yeah, it'll absolutely be worth the effort to do some benchmarks in Go for this.

**Comment by vessenes** [comment]
No problem! It strikes me that it seems worth deciding how editable / inspectable you want the compiled go source to be. If you don’t mind making random type names everywhere in the go source, the polymorphic support probably gets a lot easier. On the other hand, I imagine that that pushes against readable code as a goal.

Generally I don’t mind Go’s type pickiness, it helps us find bugs at compile time. But every couple of days, I’m like “Yes, you can compare an int32 and an int. Come on!!” 


-- 
Peter Vessenes
CEO, CoinLab Inc.
@vessenes

On November 16, 2015 at 9:07:58 AM, Oskar Wickström (notifications@github.com) wrote:

@vessenes cool, thank you for your insights! I'm thinking that monomorphisation will be A LOT simpler if odenc does inlining of these calls. Yeah, it'll absolutely be worth the effort to do some benchmarks in Go for this.

**Comment by owickstrom** [comment]
Yes, the code will be harder to read without inling. My first thoughts were something like...

```scheme
(define (map f xs)
    ...)
(define result (map identity (list 1 2 3 4)))
```

... would result in something like:

```go
func map__fn_int_int__list_int__list_int(f func int (int), xs list_int) list_int {
    ...
}
var result = map__fn_int_int__list_int__list_int(identity__int__int, list__int(1, 2, 3, 4))
```

Where each type variable resolves to a specific type a generates the rather horrible names such as `map__fn_int_int__list_int__list_int` and `identity__int__int`.

How do you mean with the type pickiness? The type safety should be the same regardless of inlining or not. I think that's more a subject of coercion and that's another story. :smiley:

**Comment by vessenes** [comment]
Yes, it was just a coercion vent. Sigh.

This is probably my poor lisp comprehension, but transforming `fn (i int)` int to `fn_int_int` makes me wonder how `fn (i, j int) int` looks as compared to `fn (i int) (int, int)`. Are you planning on implementing some sort of auto-currying? If not, I think you might need three levels of underscores.

**Comment by owickstrom** [comment]
Indeed, that sort of encoding gets tricky. However, if the compiler can keep track of the names it has generated it does not really matter, it could generate some unique name using an increment. Then it's just a hint of which types were used and it might become `fn_int_int_1` or something. I mean, there shouldn't be a case where something is dependant on the name matching the types. What do you think?

**Comment by vessenes** [comment]
Hmm, like you say, it's just a name. For some reason I was thinking you'd be parsing those names and needed to go back and forth when I made the comment. 

For readability, I'd go short on the names. But, if I were prioritizing language features, maybe I wouldn't worry about it right now, adding things the compiler has to keep track of sounds like more cognitive overhead right now.

Seems like there's a pretty simple idempotent transformation you have specified which will get (in a given scope) a guaranteed unique name out of the oden code. So, for what it's worth, I'd put off worrying about it. But that's just my style. :)

**Comment by owickstrom** [comment]
That's just what I was thinking, we'll do something simple to start with, :+1:

**Comment by owickstrom** [comment]
@vessenes: I've been crunching this a lot the last week and now there is actually something on master. I used monomorphization for polymorphic top-level definitions so the program:

```scheme

**Comment by owickstrom** [comment]
Just realized that the names get different casing. Strange... :)

**Comment by owickstrom** [comment]
Closing this as top-level polymorphic functions and monomorphization has been pretty stable even after the Haskell port.
