### ISSUE TITLE
racket 6.3 support?

### ISSUE THREAD

**Issue by wicast** [oden-lang/oden#20]
Racket 6.3 was released few days ago.But there are [some changes](http://blog.racket-lang.org/2015/11/racket-v63.html) making the oedn failed to compile.

**Comment by AlbinTheander** [comment]
Until the code is updated to support 6.3, you need to do two changes to make it work:

Replace "require unstable/hash" with "require racket/hash" in the following files:

* odenc/compiler/get-substitutions.rkt
* odenc/compiler/monomorph.rkt.

**Comment by owickstrom** [comment]
Could we do some macro-expansion trick and require different modules based on Racket version? It would be nice to support the `unstable/hash` for some time as the 6.3 release is so recent.

**Comment by owickstrom** [comment]
The Haskell port (https://github.com/oden-lang/oden/tree/haskell-port) is soon done so closing this issue. Thx!
