### ISSUE TITLE
UnificationFail in 0.2.0-RC1

### ISSUE THREAD

**Issue by AlbinTheander** [oden-lang/oden#22]
The following program won't compile with a unification fail: https://oden-playground.herokuapp.com/p/58ef1de77995e26303ad2cc1e7d6c3e6

If you change the 5 to a string, e.g. "banana", it works perfectly.

**Comment by AlbinTheander** [comment]
After a few minutes thought, I realise the impossibility of making a function that can return either an integer or a string without the language having an "Any"-like type.

**Comment by owickstrom** [comment]
Thanks anyway! :)
