### ISSUE TITLE
How to pass []{any} to a fn?

### ISSUE THREAD

**Issue by owickstrom** [oden-lang/oden#43]
```go
package main

import fmt

printAllFrom :: int -> []{int} -> ()
printAllFrom n s -> if n < 0 || n >= len(s) then () else {
  fmt.Println(s[n])
  printAllFrom(n + 1, s)
}

main -> printAllFrom(0, []{1, 3, 10, 15})
```
works but trying to pass values of type `any` instead:

```go
package main

import fmt

printAllFrom :: int -> []{any} -> ()
printAllFrom n s -> if n < 0 || n >= len(s) then () else {
  fmt.Println(s[n])
  printAllFrom(n + 1, s)
}

main -> printAllFrom(0, []{1, 3, 10, 15})
```

results in:

```
/var/folders/r6/vbhgdgrx66q_2hfspf5z8hd80000gn/T/oden-run.go23883/src/main.go:9: cannot use []int literal (type []int) as type []interface {} in argument to printAllFrom(0)
````

The `interface{}` type for `any` does not work with primitives and slices.

**Comment by owickstrom** [comment]
It would be nice not to have the `any` type at all. Not sure how to interact with `interface{}` in Go without it though.

**Comment by codygman** [comment]
You could do static analysis on a given go codebase's use of that interface{} and turn it into a sum type.

**Comment by owickstrom** [comment]
Sounds like that would be very tricky and error prone. I'm thinking we could exclude `any` from Oden (in terms of the type system and what can write) and treat `interface{}`s imported from Go as type variables. Then, after the monomorph phase, we wrap basic types in pointers to be able to pass them as `interface{}`. This is just an idea that I have, not sure if it will work in practice.

A problematic scenario with this is variadic functions. In the following case `f` would have a different set of auto-generated type variables depending on how you call it. Reusing a single type variable would be very limiting, i.e. being able to only `fmt.Println` args of the same type, so each argument needs to be a new one.

```go
// given a Go func:
f(args ...interface{})

// calls will need these types:
f(x)       // f :: forall a. a -> ()
f(x, y, z) // f :: forall a b c. a -> b -> c -> ()
f()        // f :: -> ()
```

Regarding pointer and interface types, this is probably related to https://groups.google.com/forum/#!topic/oden-lang/ramxVe-lFHw.

**Comment by owickstrom** [comment]
Closing this for now as `any` is removed. Might need to discuss related stuff regarding type variables but we'll handle it then.
