### ISSUE TITLE
Negative index for subscripts and subslices should cause error

### ISSUE THREAD

**Issue by owickstrom** [oden-lang/oden#47]
```
stuff = []{"hello", "world"}
foo = stuff[-1]
bar = stuff[0:-1]
```

Both these slice operations pass the Oden compiler but fail when compiling the Go code. This should be caught by oden.

**Comment by AlbinTheander** [comment]
The biggest problem here is that we don't simplify literal expressions. The `-1` above is expanded to `Unary Negative (Literal Int 1))`, and even if we pattern match on that, it still won't catch longer expressions like `3 * 2 - 7 * 1`.

**Comment by AlbinTheander** [comment]
I made a test of simplifying the AST before validation here: https://github.com/AlbinTheander/oden/commit/7ed8a8bb5b9c3002c22616b537c73e037b66b9a8

It only simplifies unary minus and subtraction and only direct inside the main method, but it works.

Not really sure it's a good idea, though. :-)
