### ISSUE TITLE
Require explicit quantification and syntax without # for type variables

### ISSUE THREAD

**Issue by owickstrom** [oden-lang/oden#55]
`f :: #a -> #b` should instead be written `f :: forall a b. a -> b` and the `Environment` construct should contain type variables in scope. Right now the type variable system is a separate thing.

Type constructors could have a similar syntax: `type Pair(a, b) = (a, b)` or perhaps something like `type Pair<a, b> = (a, b)` to then be applied with `Pair<int, string>` when used.

**Comment by cgag** [comment]
Why make it explicit?  I know purescript does the same thing and never understood the benefit.

**Comment by owickstrom** [comment]
In Haskell and Purescript named types and type variables reside in separate namespaces, requiring the first letter to be uppercase or lowercase, respectively. Thus, type variable clashes cannot creep into scope from other top-level definitions (AFAIK).

In Oden (right now and probably going forward) type names are not restricted to the uppercased namespace, as Oden borrows the visibility concept from Go - lowercase names are package private and first letter uppercased names are public. This makes for a confusing interplay between lowercase type names and type variables, should they not be explicit. Consider the following example:

```
type i = int

f :: i -> i
f(x) = x
```

If one removes the type alias `i` it radically changes `f`, and I think that's just a source of strange bugs. Having to write `f :: forall i. i -> i` is a minor inconvenience (please note that [the syntax is under discussion as well](https://groups.google.com/forum/#!topic/oden-lang/wU2ynjd1V6w)).

Does that make sense?

**Comment by cgag** [comment]
Ah, that makes sense.  Thanks for the explanation.  I'll take a look at the mailing list and give those alternative syntax ideas some thought.

**Comment by owickstrom** [comment]
Great, thanks!
