### ISSUE TITLE
Import syntax underdocumented

### ISSUE THREAD

**Issue by extemporalgenome** [oden-lang/oden#59]
I'm inferring that the import syntax supports an `import github.com/user/package` (no quotes) notation since the package declaration is declared to the fully qualified package name.

Why deviate from Go by not taking the import path as a string? Where is the precise import (and package) declaration syntax documented?

**Comment by owickstrom** [comment]
Very good question! I was just learning more about go imports yesterday, why they use strings. Haven't come to any conclusions yet but at a glance it seems we should have the same syntax in Oden. What do you think?

The reason for not having a string as in Go right now is simply for aesthetics, but it can of course be changed.

The lacking documentation should be fixed regardless.

**Comment by extemporalgenome** [comment]
I suspect whether it matters would very much depend on how _much_ interoperation between Oden and Go is expected, and how clean it can be. For example, could a given directory have both Go and Oden source files (in other words is both a Go package and an Oden package)? If that is desirable, then it'd be important to Oden to support whatever the official Go toolchain supports in terms of imports, both now and in the future.

Aside: indeed the authors of Go knew about such aesthetics (Google is heavily invested in Python after all, which has identifier style imports) -- strings were chosen so that the language itself didn't have to know or care about what an import means -- that's a toolchain decision. If Oden, for example, defines the import syntax as something along the lines of `\w+(/\w+)+` then it's very much a language-level decision on how imports work (which historically for Go wouldn't have made much difference [yet] in practice, but does substantially limit flexibility in theory). For example, if the Go authors wanted to allow import paths to additionally accept an optional branch name or partial revision hash, the language spec wouldn't change at all; for Oden to do the same, the language may or may not have to change, depending on how rigidly the import syntax is defined.

Whatever the case, in the spirit of Go, I recommend choosing one or the other (accept only aesthetic import paths, or accept only strings -- don't allow either, since that's a slippery slope that most languages slide down).

**Comment by owickstrom** [comment]
> For example, could a given directory have both Go and Oden source files (in other words is both a Go package and an Oden package)?

This is indeed an interesting case. There's a lot of thinking yet to be done on how Oden projects should be structured and how they work together with Go, but I hadn't thought about import paths in that context yet.

Another thing to consider is if *importing Go packages in Oden* and *importing other Oden packages in Oden* should be two different things. `import "stringy/go/pkg/path"` could be complemented with say `require stricter.oden.pkg.name`. In that case maybe it shouldn't be called *packages* in Oden, rather *namespaces*, *modules* or something else.

Thanks for your input, by the way!

**Comment by owickstrom** [comment]
Import syntax has just been changed to the following two forms:

```go
// native import
import my/oden/pkg
// foreign import
import foreign "some/go/pkg"
```

Also, the User Guide now has a section describing the behaviour and why foreign import paths needs to be strings: https://github.com/oden-lang/oden/commit/daea6c90f68d7956fb694d5b60344e906cddba95

Thanks for reporting and for your input!
