### ISSUE TITLE
Goroutine plan

### ISSUE THREAD

**Issue by vessenes** [oden-lang/oden#6]
I dig this project, and want to use it. Have you done much thinking about goroutines and channels and lispy-ness? 

I wonder if it's worth thinking about some semantic helpers. There are lots of use cases for goroutines of course, but I don't have a clear picture of how these semantics should be put into a lisp.

**Comment by owickstrom** [comment]
I'm glad to hear it!

Not that much yet, but I do like the approach in `core.async` (Clojure/ClojureScript) where "go-blocks" are expressions returning a channel, where the last expression in the block is the value in the channel. At least that's how I remembered it. I think `select`s should have similar semantics, more like a `cond` in Scheme than an imperative switch statement.

**Comment by owickstrom** [comment]
Would you be interested in writing some example use cases? It would be nice to have some code to talk about. I've only done [the ping-pong stuff in the experiments](https://github.com/oden-lang/oden/blob/master/experiments/pingpong2.oden).

**Comment by vessenes** [comment]
Definitely. Let me think through a few. Off the top of my head, there is standard channel support, a-la the ping pong example you link to, and there is also sync.WaitGroup style parallelism in which you fire off a bunch of goroutines, and then wait for completion later.

One of the common issues at large scale parallelism with Go is that channels are actually fairly heavy weight; they embed locking mechanisms for message passing, and so you don’t really want more than maybe a few thousand of them doing work. Not to mention cache-miss hell. So, it’s a common pattern in our code to fork out for, say a parallel loop, roughly n goroutines where n is the number of cores you have, and then wait for everything to come back together.

I’ll dig through some other libraries and see if I see other use cases. 

Just to summarize:

1)  funcA -> channel -> funcB
2)  funcA -> channel -> funcB -> channel -> funcA
3) wg.Add(1); go func(); wg.Wait()


-- 
Peter Vessenes
CEO, CoinLab Inc.
@vessenes

On November 16, 2015 at 9:12:00 AM, Oskar Wickström (notifications@github.com) wrote:

Would you be interested in writing some example use cases? It would be nice to have some code to talk about. I've only done the ping-pong stuff in the experiments.

**Comment by owickstrom** [comment]
All right. I actually haven't used WaitGroups more than in some exercise, so your example code will be eagerly awaited. :+1:

**Comment by vessenes** [comment]
Here's a trivial example: https://gist.github.com/vessenes/94aace435b7f75c9f6d5

the WaitGroup keeps an atomic counter of remaining wg.Done's to listen for. You can wg.Add at any time.

wg.Done() checks if there are 0 Dones left to wait for, if so, it continues, otherwise it blocks.

Note that you want to wg.Add outside of a goroutine, because it's possible that your goroutines will get spun off and you'll get to the wg.Done before any of the Add's have been processed. 

It's fine to wg.Add multiple times, in multiple places, so a for loop that fans out would have as its first line inside the loop wg.Add(1), and as the last line inside the goroutine wg.Done().

Let me know if this is enough of a help!

**Comment by vessenes** [comment]
I updated the gist to include a for loop fanning out.

**Comment by owickstrom** [comment]
Ah I see, that's interesting. My first thought is that it's probably a good idea to support these constructs as-is in the basic FFI with Go and then, when Oden becomes more powerful (this is starting to sound like Norse Mythology already), one could build higher-level constructs for these patterns. It kind of feels like there's a nice macro construct waiting to be written on top of this.

**Comment by owickstrom** [comment]
Closing this and moving high-level discussions to https://groups.google.com/forum/#!forum/oden-lang.
