### ISSUE TITLE
math: power function

### ISSUE THREAD

**Issue by voutasaurus** [oden-lang/oden#61]
Any plans to implement ** (aka ^) for numeric types (or even just int)?

By the way, Oden looks really cool. :)

**Comment by owickstrom** [comment]
Do you mean an infix version of https://golang.org/pkg/math/#Pow? In that case no, as it's in a specific importable package in Go. Will try to keep the predefined "special" things to a minimum, at least for now.

Thanks for asking and for the kind words! :)

**Comment by voutasaurus** [comment]
Yeah that's what I meant. It's sort of awkward though because it's float only and rounding is awkward. Thanks for the response though! :)

**Comment by owickstrom** [comment]
Ah, you want a polymorphic version for different numeric types?

**Comment by voutasaurus** [comment]
It's one of those things that I rarely use so it's not a huge problem but when I see something like Haskell it's one of the first things I try. I was mostly wondering how tricky it would be.

**Comment by owickstrom** [comment]
OK! Right now a bit involved. In a distant future Oden might have something like type classes and the possibility to define numeric operations in terms of type classes. That would be very nice. :)

**Comment by owickstrom** [comment]
Closing this for now, hopefully we can implementing something with standard Oden constructs when it's more mature.
