### ISSUE TITLE
Merge TUncurriedFn and TVariadicFn

### ISSUE THREAD

**Issue by AlbinTheander** [oden-lang/oden#65]
When importing functions from Go packages, they become either `TUncurriedFn` or `TVariadicFn` depending on whether the function is variadic or not.

Later on, code that handles theses two types are very similar throughout the code base. The main difference is that code around `TVariadicFn` needs to handle the variadic parameter as well.

It would make the code simpler if we could just handle all imported Go functions as one type which would be like `TVariadicFn` but could handle the absence of the variadic parameter.

Maybe call it `TForeignFn`.

**Comment by owickstrom** [comment]
It's probably a good time to do this now (or soon).
