### ISSUE TITLE
question about reusing golang code

### ISSUE THREAD

**Issue by joeblew99** [oden-lang/oden#67]
i am not knowledgable in compilers. But i want a scripting language for go.
Oden looks nice too because its functional.

My question relates to reusing existing golang code.
Can i expose existing golang code to the upstream oden ? Or is it the other way around ?

**Comment by owickstrom** [comment]
If you have installed a Go package `your/pkg` (by running `go install <your/pkg>`) and you use the same GOPATH when running Oden then `your/pkg` will be importable. You can use `oden run <file>` if you do not want to compile separately.

**NOTE:** Oden is a young project and the importer is still very limited, so I doubt it will be useful for you at the moment. If you run with the `-W` flag you'll see warnings about which definitions that couldn't be imported.

**Example when importing the fmt package:**
```bash
$ oden run -W program-that-uses-fmt.oden
warning: Some definitions could not be imported from package `fmt`:
  `Stringer` (Interfaces are not supported)
  `State` (Interfaces are not supported)
  `Scanner` (Interfaces are not supported)
  `ScanState` (Interfaces are not supported)
  `GoStringer` (Interfaces are not supported)
  `Fscanln` (Interfaces are not supported)
  `Fscanf` (Interfaces are not supported)
  `Fscan` (Interfaces are not supported)
  `Fprintln` (Interfaces are not supported)
  `Fprintf` (Interfaces are not supported)
  `Fprint` (Interfaces are not supported)
  `Formatter` (Interfaces are not supported)
  `Errorf` (Interfaces are not supported)
For more information see: https://github.com/oden-lang/oden/wiki/Warning:-Go.UnsupportedTypesWarning
```

However, this is planned to work in the future. Don't hesitate to ask if you need help. The mailing list is a better place for these kinds of questions: https://groups.google.com/forum/#!forum/oden-lang

**Comment by joeblew99** [comment]
thanks. I am willing to give this a go (haha )

So i need to write some oden code to call / use the golang code right ? It uses reflection ? Just trying to grasp how it all works a bit under the covers.

**Comment by owickstrom** [comment]
You can check out the programs in https://github.com/oden-lang/oden/tree/master/regression-test/src to get a feel of what is possible. All of them import the Go `fmt` package.

The Oden compiler knows what's in the imported packages and it generates the needed Go code to call functions etc.

**Comment by joeblew99** [comment]
ok thanks for your patience. I will have a look

**Comment by owickstrom** [comment]
I'm glad you are interested in Oden,  so it's no trouble. :)

**Comment by joeblew99** [comment]
:) cheers
