### ISSUE TITLE
Higher-kinded types?

### ISSUE THREAD

**Issue by Heimdell** [oden-lang/oden#68]
Do you plan to implement the subject? I cannot see any kind-related stuff around definitions of `Type`.

**Comment by owickstrom** [comment]
If you mean type constructors/parametrized types, then yes. Right now there's only *, or "proper type" as I understand it's called as well. 

Not sure when this is coming but I've been preparing for it so it's hopefully not that far away. Probably going to do extensible records first, however.

**Comment by owickstrom** [comment]
I am working on extensible records right now and basic support for parameterized types will probably come out of that work very naturally. :+1:

**Comment by owickstrom** [comment]
Closing this. If you want to start a high level discussion on the subject please do so at https://groups.google.com/forum/#!forum/oden-lang. Thank you!
