### ISSUE TITLE
Example from documentation does not compile

### ISSUE THREAD

**Issue by jBugman** [oden-lang/oden#72]
Snippet from http://oden-lang.org/user-guide/writing-oden-code.html

```
package main
import fmt

result = shout("hello, world")

shout :: string -> string
shout(s) = s ++ "!"

main() = fmt.Println(result)
```

does not compile with ```error: `shout` is not in scope```

It can be fixed by changing function declaration ordering.

Is example wrong or implementation?

**Comment by owickstrom** [comment]
The example is wrong. In the old  0.1.x compiler out-of-order definitions were possible but they are not anymore. It should be supported, but for now we should change the example. I'll fix this tonight.

Thanks for reporting!
