### ISSUE TITLE
Substitution error with records and fmt.Println

### ISSUE THREAD

**Issue by owickstrom** [oden-lang/oden#75]
Depending on how `fmt.Println` is wrapping the entire `if` or if it's called in the branches the substitution fails:

```go
package main

import fmt

test = {
  a = {
    visible = true,
    name = "a"
  },
  b = {
    visible = false,
    name = "b"
  }
}

// This works:
describe1(thing) = fmt.Println(if thing.visible then thing.name else "<hidden>")

// This fails with:
// error: Substitution failed for type variable  _t5
describe2(thing) = if thing.visible then fmt.Println(thing.name) else fmt.Println("<hidden>")

main() = {
  describe1(test.a)
  describe1(test.b)
  describe2(test.a)
  describe2(test.b)
}
```

Haven't had time to try to boil this down even further, not sure if some part is irrelevant here...

**Comment by AlbinTheander** [comment]
This could be related to the return value of `fmt.Println`. It's signature is `func Println(a ...interface{}) (n int, err error)` which we currently treat as `int`.

I guess if we solve #62 to handle multiple return values and either add support for interfaces or solve #76 to be able to treat them as unit functions, this will work.

**Comment by owickstrom** [comment]
I've tried this after merging the multiple return value stuff, no change. I think this has something to do with the argument type of `fmt.Println` being `any`.  In the following example the string concatenation, probably forcing the type to be `string`, solves the substitution error. Not that it only occurs for the second argument of `fmt.Println`. There's probably something weird going on with variadic functions and/or `any`.

```go
package main

import fmt

type Point = { x : int, y : int }

center = { x = 0, y = 0 }

printPoint(p) = fmt.Println(p.x, p.y ++ "") // string concatenation makes it work

main() = printPoint(center)
```

**Comment by AlbinTheander** [comment]
If you look at the original code, both `describe1` and `describe2` are inferred to have type `forall a. {visible: bool | a} -> ()`, i.e. the name field is not in the signature at all.

And, if you remove the `name` field from both `a` and `b`, Oden will happily compile `describe1`. Go won't run it, of course, but will complain about the `name` field missing.

So something goes wrong when inferring the type of the arguments.

**Comment by AlbinTheander** [comment]
What is odd is that compilation fails even if you add an explicit type for `describe2`:

```go
describe2 : forall a. {visible: bool, name: string | a} -> ()
describe2(thing) = if thing.visible then fmt.Println(thing.name) else fmt.Println("<hidden>")
```

**Comment by AlbinTheander** [comment]
I think I boiled it down to this code:

```go
package main

import fmt

a = {p1 = "p1", p2="p2"}


describe : {p1: string, p2: string} -> ()
describe(thing) = {
  fmt.Println(thing.p1)
  fmt.Println(thing.p2)
}

main() = describe(a)
```
(The type signature of `describe` makes no difference to the problem.) The second `Println` line will fail with `src/main.oden:10:15: error: Unexpected polymorphic type '_t6'`.

In both cases it correctly finds the type of `thing` (`{p1: string, p2: string}`). But for some reason, it thinks that the type of `thing.p2` is the unbound type variable `_t6`. Switching the printing lines will give the same error on the second line again (this time referring to `thing.p1`.)

It doesn't have anything to do with the `if` expression. My guess is something with the same struct being referenced several times within a block.
