### ISSUE TITLE
Indentation in generated go code is unreasonable

### ISSUE THREAD

**Issue by AlbinTheander** [oden-lang/oden#79]
When using `let` statements in Oden, the resulting indentation degenerates very quickly.

The following simple Oden code:

```go
package main

import fmt

main : -> ()
main() = let x = 5 y = 3 in
  fmt.Println(x + y)
```

produces the following go code
```go
package main
import fmt "fmt"
func main() {(func() struct{} {var x int = 5
                               return (func() struct{} {var y int = 3
                                                        fmt.Println([]interface{}{(x + y)}...)
                                                        return struct{}{}})()})()}
```

Line four is indented 32 spaces and line five with 57. More `let` assignments and the code disappears off your screen.

Even though reading the code is not a primary concern, I'd appreciate a bit more readability.

**Comment by owickstrom** [comment]
Totally agree on this. Should we perhaps start by creating the separate AST for Go code and then improving the pretty print of that?

**Comment by AlbinTheander** [comment]
Sounds like a good approach.

**Comment by owickstrom** [comment]
Related to #84.
