### ISSUE TITLE
Compound Types

### ISSUE THREAD

**Issue by vishesh** [oden-lang/oden#8]
Have you thought much about adding compound types like structures or sum types? Thinking about structures could be useful for Go FFI too. I think lispy structures can in general can correspond well with Go structures.

**Comment by owickstrom** [comment]
Yes, Oden needs something mapping to Go structs at the very least. And I agree regarding the lispy struct concept, it would probably map very well. I'm not an expert on Scheme standards, but I think [this document](https://www.gnu.org/software/guile/manual/html_node/SRFI_002d9-Records.html) is related?. The predicate function won't be of much use but the *accessors* and *functional setters* would be nice to keep in a similar way.

We do need some way of generating the field access/assignment in Go, i.e. `foo.bar` and `foo.bar = 1`. In the Scheme example they generate specific accessors `foo-bar` but have generic `set-field` and `set-fields` for all structure types.

Another thing to consider is the mutability/immutability aspect. I've barely touched upon that general subject in the Motivations & Goals (that should be clarified ASAP). I think Oden should provide immutable data structures, both for user-defined compound types and for collections, and still support "mapped-to-Go" mutable data structures like structs, slices etc. Immutability should be the default.

**Comment by owickstrom** [comment]
That's sounds good!

**Comment by joeblew99** [comment]
+ immutable

But how can an open immutable data structure map to a mutable golang data structure ?
I guess it all depends if you doing forward engineering / codegen ?

**Comment by owickstrom** [comment]
@joeblew99 not sure right now, but yes that weighs in as well as the fact that interoperability from Go to Oden is not a priority. Perhaps the immutability is only enforced at compile time. Or we could use structs in separate packages to represent immutable structures and hide everything behind public accessors and some kind of cloning facility. Do you have any ideas?

**Comment by joeblew99** [comment]
@owickstrom 
i like the idea of mapping immutable on top of non immutable. its what i do now for projects often. 
i have a stab at it 
Top layer is like an immutable orchestration layer that is coded up to call lots of microservices to do whatever. It has its own struts, and a WAL (write ahead log), always adding data after a orchestration has ended.
Micrososervices layer is not immutable. I dont care what these funky dudes do , which is the point.
Outout from the orchestration writes to the WAL. Generally it push data up to some client, who may also have a WAL. 
Clients outside the system  calls back in, hits the orchestration layer and it all happens again.

What makes all it easy if each microservice exposed PB or something i can reflect on, to generate my orchestration layer. For Oden, i dont know how it binds to the go code. Should look, but right now am on a rush to finish something. 

i bet i am not explaining this well ?

**Comment by Heimdell** [comment]
For setters/getters (to/from immutable values) you could have/generate lenses:
```haskell
> data Lens s a = Lens { get :: s -> a, modify :: (a -> a) -> (s -> s) }
> let outer `compose` inner = Lens { get = get inner . get outer, modify = modify outer . modify inner }
> :t compose
compose :: Lens s a -> Lens a a1 -> Lens s a1
```
`(.)` is a function composition here.

By the way, where can I take a sneak peek onto type system specification?

**Comment by owickstrom** [comment]
Thanks for the feedback! There's the Language Reference at http://oden-lang.org/user-guide/language-reference/. Very much work in progress. :)

**Comment by owickstrom** [comment]
Closing this and moving high-level discussions to https://groups.google.com/forum/#!forum/oden-lang.
