### ISSUE TITLE
Go functions with multiple return values and no arguments cause type mismatch

### ISSUE THREAD

**Issue by owickstrom** [oden-lang/oden#82]
Given the Go package *stuff*:

```go
package stuff

func GiveMeStrings() (string, string) {
        return "ok", "!"
}
```

And an Oden program using the package like this:

```go
package tuplereturn/main

import fmt
import stuff

strings = stuff.GiveMeStrings()

main() = {
  fmt.Println(strings)
}
```

You get a compilation error:

```
src/tuple-return.oden:6:11: error: Types do not match
For more information see: https://github.com/oden-lang/oden/wiki/Error:-Infer.UnificationMismatch
```

However, adding a parameter to the Go function:

```go
package stuff

func GiveMeStrings(s string) (string, string) {
        return s, "!"
}
```

And calling it with an argument:

```go
package tuplereturn/main

import fmt
import stuff

strings = stuff.GiveMeStrings("ok")

main() = {
  fmt.Println(strings)
}
```

... works. The first version should work as well.

**Comment by owickstrom** [comment]
@AlbinTheander ideas?

**Comment by AlbinTheander** [comment]
It's very weird. It tries to unify `[TCon <meta> (FQN [] (Identifier "string"))]` and `[]`, which fails (obviously). But exactly how it ends up with those types, I'm not sure.

I'm away over the weekend. Will try to look into it afterwards.

**Comment by owickstrom** [comment]
It was quite simple, fixed now. :)
