### ISSUE TITLE
Immutable Collections

### ISSUE THREAD

**Issue by owickstrom** [oden-lang/oden#9]
- [ ] Document this in the Goals docs.
- [ ] Describe this issue in much more detail.

Immutable data structures should be the default in Oden. Mutable ones, those already existing in Go, should be available but not the idiomatic choice (we do have to have them for FFI). Something like Clojure where immutable lists, vectors and maps are the standard but you can construct a `java.util.ArrayList` and mutate it if you need that.

Again, focus on semantics rather than performance. Oden does not need the most performant structural sharing data structures **to begin with**, it just needs something that has the semantics we want.

**Comment by owickstrom** [comment]
For the sake of interoperability with Go the focus to begin with will be on supporting the standard mutable data structures first (array, slice, map). The immutable data structures will most likely be built in terms of the mutables ones anyway so it seems OK.

**Comment by Heimdell** [comment]
> The immutable data structures will most likely be built in terms of the mutables ones

I do not recomment this. Look onto java's immutable collections. They are more succinct in space then their mutable counterparts and do not require any locks for thread synchronization.

**Comment by owickstrom** [comment]
Closing this and moving high-level discussions to https://groups.google.com/forum/#!forum/oden-lang.
