### ISSUE TITLE
OS X binary links to dynamic libpcre

### ISSUE THREAD

**Issue by dottedmag** [oden-lang/oden#92]
OS X binary links to dynamic libpcre (using explicit path `/usr/local/opt/pcre/lib/libpcre.1.dylib`), which causes headache due to lack of the library at this exact path.

It would be useful to have it linked statically.

**Comment by owickstrom** [comment]
Thanks for reporting!

I believe getting the static linking to work with `libimporter.dylib`, the custom Go library we use to resolve Go imports, will be troublesome. I did link to it statically before but it didn't work on Linux and caused a lot of headache with Stack and Cabal. Dynamic linking has worked smoother, until now at least. :)

When I build Oden locally the path to libpcre is `/usr/local/lib/libpcre.1.dylib` as it should be. The binary that get's the explicit path is built by Travis. I'm not sure why it is explicit though.

**Comment by dottedmag** [comment]
This kind of distribution should either use libraries available in the base OS (`/usr/lib/libpcre.0.dylib`, though note different ABI version), or bundle them. Relying on Brew/MacPorts is asking for trouble (unless the installation itself is performed through Brew/MacPorts).

**Comment by owickstrom** [comment]
Oh, yeah you're right, the path I referred to is Brew-specific, forget about that.

OK, but if it's possible to get the Stack build to only statically link pcre then maybe that'll work. I'll bash my head at it for a while. :)

**Comment by dottedmag** [comment]
I'll check it out as well.

**Comment by owickstrom** [comment]
PCRE is now bundled with the distribution and included using `DYLD_LIBRARY_PATH`, so closing this. Thanks!
